run:
		gcc ADT/machine/wordmachine.c ADT/list/dynamic_list.c ADT/setmap/set.c ADT/setmap/map.c ADT/machine/charmachine.c console.c ADT/queuestack/queue.c ADT/queuestack/stack.c FUNGSI/start.c FUNGSI/load.c main.c -o main
		./main